### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by lucaasgaabriel** [lucaasgaabriel/AmoraPetshop-Projeto-Estacio#5]
Criação do diagrama de classes conforme análise de requisitos. Está na pasta Documentação do Projeto.

**Comment by ArthurMartinsMarcalPassos** [comment]
Foi feito a diagramação e o pull request constando as classes, Animal, Cliente, Agendamento, Produto e Funcionário que consta na documentação de análise de requisitos.
