### ISSUE TITLE
Modelagem do banco de dados

### ISSUE THREAD

**Issue by lucaasgaabriel** [lucaasgaabriel/AmoraPetshop-Projeto-Estacio#8]
Criação da modelagem do banco de dados da Amora Petshop

**Comment by ebertlc** [comment]
Modelagem realizada conforme a analise de requisitos e o diagrama de classes, contendo:

- Diagrama de modelo Conceitual; 
- Diagrama de modelo Lógico;
- Exemplo de criação do modelo Físico.
